// <auto-generated />
using System;
using Hoops.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hoops.Infrastructure.Migrations
{
    [DbContext(typeof(hoopsContext))]
    [Migration("20260126180000_IncreasePayTypeLength")]
    partial class IncreasePayTypeLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration uses raw SQL and doesn't change the model
            // Inheriting from the previous migration's model
        }
    }
}
