using Hoops.Core.Models;
using Hoops.Infrastructure.Data;
using Hoops.Infrastructure.Repository;
using Microsoft.EntityFrameworkCore;
using Xunit;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Hoops.Infrastructure.Tests
{
    public class DirectorRepositoryTest
    {
        private DirectorRepository CreateRepositoryWithSeededContext(string? dbName = null)
        {
            var options = new DbContextOptionsBuilder<hoopsContext>()
                .UseInMemoryDatabase(databaseName: dbName ?? Guid.NewGuid().ToString())
                .Options;
            var context = new hoopsContext(options);

            // Add some test data
            context.Directors.AddRange(new List<Director>
            {
                new Director
                {
                    DirectorId = 1,
                    CompanyId = 1,
                    PersonId = 101,
                    Seq = 1,
                    Title = "Board President",
                    CreatedDate = DateTime.Now,
                    CreatedUser = "test"
                },
                new Director
                {
                    DirectorId = 2,
                    CompanyId = 1,
                    PersonId = 102,
                    Seq = 2,
                    Title = "Vice President",
                    CreatedDate = DateTime.Now,
                    CreatedUser = "test"
                }
            });
            context.SaveChanges();
            return new DirectorRepository(context);
        }

        [Fact]
        public void GetById_ReturnsCorrectDirector()
        {
            // Arrange
            var repo = CreateRepositoryWithSeededContext();

            // Act
            var director = repo.GetById(1);

            // Assert
            Assert.NotNull(director);
            Assert.Equal(1, director.DirectorId);
            Assert.Equal("Board President", director.Title);
        }

        [Fact]
        public void Insert_CreatesNewDirector_WithAutoGeneratedId()
        {
            // Arrange
            var repo = CreateRepositoryWithSeededContext();
            var newDirector = new Director
            {
                DirectorId = 0, // Should be auto-generated
                CompanyId = 1,
                PersonId = 103,
                Seq = 0, // Should be auto-generated
                Title = "Treasurer",
                CreatedDate = DateTime.Now,
                CreatedUser = "test"
            };

            // Act
            var created = repo.Insert(newDirector);
            repo.SaveChanges();

            // Assert
            Assert.NotNull(created);
            Assert.Equal(3, created.DirectorId); // Should be next ID
            Assert.Equal(3, created.Seq); // Should be next Seq
            Assert.Equal("Treasurer", created.Title);
        }

        [Fact]
        public void Update_ModifiesExistingDirector()
        {
            // Arrange
            var repo = CreateRepositoryWithSeededContext();
            var director = repo.GetById(1);
            director.Title = "Updated President";

            // Act
            var updated = repo.Update(director);
            repo.SaveChanges();

            // Retrieve again to verify
            var retrieved = repo.GetById(1);

            // Assert
            Assert.NotNull(updated);
            Assert.Equal("Updated President", retrieved.Title);
        }

        [Fact]
        public void GetAll_ReturnsAllDirectorsForCompany()
        {
            // Arrange
            var repo = CreateRepositoryWithSeededContext();

            // Act
            var directors = repo.GetAll(1);

            // Assert
            Assert.NotNull(directors);
            Assert.Equal(2, directors.Count);
        }

        [Fact]
        public void Delete_RemovesDirector()
        {
            // Arrange
            var repo = CreateRepositoryWithSeededContext();
            var director = repo.GetById(1);

            // Act
            repo.Delete(director);
            repo.SaveChanges();

            // Retrieve again to verify
            var retrieved = repo.GetById(1);

            // Assert
            Assert.Null(retrieved);
        }
    }
}
