name: Deploy to Azure App Service


on:
  push:
    branches:
      - develop  # Change this if you want it to trigger on a different branch
      
permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'  # Adjust this based on your .NET version
  
      - name: Build .NET API
        run: dotnet build --configuration Release
  
      - name: Publish .NET API
        run: dotnet publish src/Hoops.Api/Hoops.Api.csproj -c Release -o ./publish
  
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hoops-api-dev'
          package: './publish'

      - name: List deployed files
        run: ls -R /home/site/wwwroot




