name: Deploy Azure Functions

on:
  push:
    branches:
      - develop
      - main
      - master

env:
  DOTNET_VERSION: 9.0.x
  FUNCTIONS_PROJECT: src/Hoops.Functions/Hoops.Functions.csproj
  PUBLISH_DIR: publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore Hoops.sln

      - name: Build
        run: dotnet build Hoops.sln -c Release --no-restore

      - name: Test (fast)
        run: dotnet test Hoops.sln -c Release --no-build --filter "TestCategory!=Slow" --nologo

      - name: Publish Functions
        run: dotnet publish ${{ env.FUNCTIONS_PROJECT }} -c Release -o ${{ env.PUBLISH_DIR }}

      - name: Archive package
        run: |
          cd ${{ env.PUBLISH_DIR }}
          zip -r ../functions.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: functions
          path: functions.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: functions

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Select Function App by branch
        id: selectapp
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "app_name=hoops-functions-dev-djeqhegwahbua7eq" >> $GITHUB_OUTPUT
          else
            echo "app_name=hoops-functions-prod" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to Azure Functions (zipDeploy)
        uses: azure/functions-action@v1
        with:
          app-name: ${{ steps.selectapp.outputs.app_name }}
          package: functions.zip
